### ISSUE TITLE
TextInputLayout's EditText hint font still not changed 

### ISSUE THREAD

**Issue by MuBoori** [MarcinOrlowski/Fonty#2]
I've EditText wrap around TextInputLayout but the hint font still the same as the old one.      

     <android.support.design.widget.TextInputLayout
          android:id="@+id/input_layout_password"
          android:layout_width="match_parent"
          android:layout_height="wrap_content">
          
          <EditText
              android:id="@+id/password_editText"
              android:layout_marginBottom="10dp"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:textAlignment="center"
              android:hint="@string/text_password"/>
          
    </android.support.design.widget.TextInputLayout>

**Comment by MarcinOrlowski** [comment]
`TextInputLayout` is not directly supported at the moment. I will check if it can be added.

**Comment by MarcinOrlowski** [comment]
Added in 1.2.0. Thanks for suggestion.

**Comment by MarcinOrlowski** [comment]
BTW: when you use `TextInputLayout` you should also be using `android.support.design.widget.TextInputEditText` instead of regular `EditText`

**Comment by MuBoori** [comment]
Thanks lot, thanks for the recommendation.
