### ISSUE TITLE
Problem in recyclerview adapter

### ISSUE THREAD

**Issue by AnguelSC** [MarcinOrlowski/Fonty#8]
Hello,
I'm using Fonty in an adapter in my recyclerview, but it only affects (sometimes) the first element or all but not the last one.

[Capture: Design](http://prntscr.com/h8sfgb)
[Capture: Code](http://prntscr.com/h8sete)

**Comment by MarcinOrlowski** [comment]
You should apply Fonty to `ViewGroup` you inflated (what you got returned from the `Inflater`) **not** the parent container which is what you do now.

**Comment by Odaym** [comment]
you don't get back a viewgroup from inflating, you get back a View, your setFonts takes either Activity or ViewGroup.
